<?php

    class Design_Share extends CI_Controller{
        
        public function __construct() {
            
            #when the class is called run the parent's constructor function to inherit from parent
            #class
            parent::__construct();
            
            #start a session for the current user
            $this->load->library('session');
            
        }//end __Construct Function
        
        public function view($page="list",$data=array()) {
            
            #uses conditional to check if request page exists
            if(!file_exists('application/views/pages/'.$page.'.php')) {
                
                #if page doesn't exist, show the 404 message
                show_404();
                
            }
            
            #uses conditional to check if the user is logged in when the view method is called
            if($this->session->userdata('login_state') == TRUE) {
                #if a user is logged in
                
                #loads the header and footer include files for the page, and the desired page
                $this->load->view('html_templates/header.inc');
                $this->load->view('pages/'.$page.'.php',$data);
                $this->load->view('html_templates/footer.inc');
            }else{
                #if a user isn't logged in
                
                #loads the header and footer include files for the page, and the home page sign-in forms
                $this->load->view('html_templates/header.inc');
                $this->load->view('pages/home.php',$data);
                $this->load->view('html_templates/footer.inc');
            }   
        
        }//end View Function
        
        public function signup() {
            
            #creates variable to hold a reference to the CodeIgniter $_POST variable
            $post = $this->input->post(NULL,TRUE);
            
            #loads the model for sending database queries
            $this->load->model('designshare_model');
            
            #registers the new user in the database, saves returned user info for login
            $new_user = $this->designshare_model->registerUser($post);
            
            #log the new user in using the getUserByPassword function and the $new_user_info array values
            $user = $this->designshare_model->getUserByPassword($new_user['user'],$new_user['password']);
            unset($post['signup_button']);
            $this->view('list');
            
        }//end SignUp Function
        
        public function updateUser() {
            
            #loads the URL helper class so the base_url() method can be used
            $this->load->helper('url');
            
            #creates variable to hold a reference to the CodeIgniter $_POST variable
            $post = $this->input->post(NULL,TRUE);
            
            #loads the model for sending database queries
            $this->load->model('designshare_model');
            
            $this->designshare_model->updateUserInfo($post);
            $this->view('list');
            
        }//end UpdateUser Function
        
        public function deleteUser() {
            #loads the URL helper class so the base_url() method can be used
            $this->load->helper('url');
            
            #creates variable to hold a reference to the CodeIgniter $_POST variable
            $post = $this->input->post(NULL,TRUE);
            
            #loads the model for sending database queries
            $this->load->model('designshare_model');
            
            #deletes user
            $this->designshare_model->deleteUser();
            
            #redirects page back to home page
            header('Location: '.base_url('index.php'));
            #exits the current function 
            exit;
            
        }//end DeleteUser Function
        
        public function designs() {
            
            #loads the model for sending database queries
            $this->load->model('designshare_model');
            
            #stores the API content for displaying the list of artwork
            $shots = $this->designshare_model->getListFromAPI();
            
            #displays the designs page and passes in the data for the list items
            $this->view('designs',$shots);
            
        }//end Designs Function
        
        public function details($design_id) {
            
            #loads the model for sending database queries
            $this->load->model('designshare_model');
            
            #holds the current user's userId
            #used to check for comments generated by the current user
            $user_id = $this->session->userdata('userId');
            
            #requests the design-specific details for the design id number selected by the user
            $details = $this->designshare_model->getDetailsFromAPI($design_id);
            
            #loads any comments for this design that might be stored in the database
            $comments = $this->designshare_model->loadComments($design_id);
            
            #creates a new array for holding all the detail page's content
            $detail_page_content = array('user'=>$user_id,'details'=>$details,'comments'=>$comments,'design_id'=>$design_id);
            
            #calls the view function and passes the $detail_page_content array that holds API values
            #and the comments for the design
            $this->view('detail',$detail_page_content);
            
            
        }//end Details Function
        
        public function postComment($design_id) {
            
            #loads the url helper
            $this->load->helper('url');
            #loads the model for querying the database
            $this->load->model('designshare_model');
            
            #stores the post array values from the comment form
            $post = $this->input->post(NULL,TRUE);
            
            #stores the comment text that was input
            $input = $post['comment_input'];
            #stores the userId of the user that is posting the comment
            $user_id = $this->session->userdata('userId');
            
            #uses conditional to check if a comment was actually submitted to the database
            if(!empty($input)) {
                #if the comment input isn't empty
                
                #create an array that holds user and comment info
                $comment_info = array('input'=>$input,'user'=>$user_id,'design'=>$design_id);
                
                #call the postComment method of the model to add the comment to the database
                $this->designshare_model->postComment($comment_info);
            }
            
            #redirect the user back the details page for the design,
            #now (possibly) updated with the new comment
            redirect(base_url('index.php/details/'.$design_id));
            
        }//end PostComment Function
        
        public function deleteComment($comment_id,$design_id) {
            #loads the URL helper class so the base_url() method can be used
            $this->load->helper('url');
            
            #stores the post array values from the delete_comment_form
            $post = $this->input->post(NULL,TRUE);
            
            #uses conditional to check if the delete button has been clicked
            if($post['delete_comment_button']) {
                #if the delete_comment_button is present in the post array
                
                #loads the model for sending database queries
                $this->load->model('designshare_model');
                
                #calls the deleteComment method from the model and deletes the comment with the
                #matching comment_id value
                $this->designshare_model->deleteComment($comment_id);
                
                #removes the delete_comment_button from the post array
                unset($post['delete_comment_button']);
                
                #redirects the user back to the details page of the design they were viewing
                redirect(base_url('index.php/details/'.$design_id));
            }else{
                #if the delete button hasn't been clicked
                
                #view the delete button screen to allow users to delete the comment
                $this->view('delete_comment');
            }
            
        }//end DeleteComment Function
    }

?>