<!DOCTYPE HTML>
<html>
    <head>
        <title>DesignShare | Reveal and Share Your Inspiration</title>
        <meta name="description" content="DesignShare allows you to find and share artwork and design that moves you.">
        <meta name="author" content="Donald Simmons">
        

        
        <link href="<?php echo base_url('libraries/designshare_theme.min.css') ?>" type="text/css" rel="stylesheet" />
        <link href="<?php echo base_url('libraries/jquery.mobile.structure-1.3.0.min.css') ?>" type="text/css" rel="stylesheet" />
        <link href="<?php echo base_url('css/main.css'); ?>" type=text/css rel="stylesheet" />
 
            
    </head>
    <body>
        
