<!DOCTYPE HTML>
<html>
    <head>
        <title>DesignShare | Reveal and Share Your Inspiration</title>
        <meta name="description" content="DesignShare allows you to find and share artwork and design that moves you.">
        <meta name="author" content="Donald Simmons">
        
        <?php
            $this->load->helper('url');
        ?>
        
        <link href="<?php echo base_url('libraries/jquery.mobile-1.3.0.min.css') ?>" type="text/css" rel="stylesheet" />
            
    </head>
    <body>
        <header>
            <h3>DesignShare</h3>
        </header> <!-- End Header -->
        <div id="container">